baseURL = "https://vi-kh.github.io"
languageCode = "en-us"
# title = "Some of my writings, and my CV"
title = "DOCUMENTING and surroundings / Около ДОКУМЕНТИРОВАНИЯ"
theme="archie"
copyright = "© Viktor-Kh"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "На этом сайте я размещаю материалы о том, что мне кажется интересным или полезным. Ими можно и просто пользоваться, и рассматривать в качестве примеров моей работы. Как правило, делаю я их и на английском (международном) языке, и на русском (моем родном), при этом указываю для таких «парных» материалов одну и ту же дату. Исключением будут адаптированные переводы, которые я планирую. Очевидно, готовить их я буду только на одном, целевом языке, а на оригиналы – давать ссылки."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vi-kh"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/v-jur-kh"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All articles & posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About the author"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags (for subjects, sections, etc.)"
url = "/tags"
weight = 4
